### PR TITLE
Close #10. Add link to anchors via js

### LINKED ISSUE #10: add per-article anchors, so that people can link to individual articles

### PR DESCRIPTION
**Pull request by fcurella**
I'm not 100% sure of how the project's build process work, so please correct me if I'm doing anything wrong.

### CODE REVIEW

**Comment by zacchiro** [comment]
Thanks for your pull request!

The build integration is just fine. As a nitpick I'd rather have the script element within HTML head rather than at the end of the body, but that's just a minor cosmetic issue.

More importantly though, your patch doesn't work for me. When opening the generated HTML in browser (via a file:/// URL) I get a JavaScript console error:

> Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined
> in spite of the fact that document is defined and it has the mentioned property if tried interactively. Maybe a load time issue?

Does this actually work for you? (I'm testing with Chromium on Debian/testing).

Note: if you prefer, as the final rendering is done within a jQuery-enabled template, relying on jQuery would totally be fine too (even though it would make it harder to test it locally).

**Comment by zacchiro** [comment]
(sorry, closed by mistake, I only wanted to comment)

**Comment by fcurella** [comment]
Yeah, most definitely a load time issue. I can try attaching to the 'load' event directly without using jquery

**Comment by fcurella** [comment]
@zacchiro I've tested my latest changes by pushing some manual changes to my `gh-pages` branch. Simply running `make public_html && make publish` won't work because the URLs point to your domain.

The reason why I've put the script at the bottom is simply old habit. With big scripts (which is not this case), there is a slight improvement in the percepted loading time because the browser won't delay the rendering until the script is downloaded. Obviously in this case the point is moot because the script is just a dozen lines ;)

**Comment by fcurella** [comment]
@zacchiro do you need a PR for the [gh-pages theme](https://github.com/zacchiro/costituzione/blob/gh-pages/_includes/themes/twitter/default.html) as well?

**Comment by zacchiro** [comment]
In the end I preferred a jquery-based solution, as it's likely it will be needed in the future for other stuff.
So I've just fixed #10 pushing commit 4621ae09da2dae91c0292459e389d69ec67cb11b.
I'm closing this pull request accordingly.

(However, I'd love to still have the CC-0 footer that you added. So it'd be great if you could submit a separate pull request for that. Thanks!)

**Pull request closed without merging**
